// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kanusaoft1.Models;

namespace kanusaoft1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220210163941_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kanusaoft1.Model.location", b =>
                {
                    b.Property<string>("address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("address");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("kanusaoft1.Model.supplement", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("locationaddress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.HasIndex("locationaddress");

                    b.ToTable("supplements");
                });

            modelBuilder.Entity("kanusaoft1.Model.supplement", b =>
                {
                    b.HasOne("kanusaoft1.Model.location", "location")
                        .WithMany("supplement")
                        .HasForeignKey("locationaddress");
                });
#pragma warning restore 612, 618
        }
    }
}
